# Generated by Django 4.2.18 on 2025-01-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Question", new_name="FAQ",),
    ]
