# Generated by Django 4.2.18 on 2025-01-31 17:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_rename_question_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq", options={"verbose_name": "FAQ", "verbose_name_plural": "FAQs"},
        ),
        migrations.RemoveField(model_name="faq", name="created_at",),
        migrations.AddField(
            model_name="faq",
            name="answer_bn",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Answer in Bengali"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Answer in Hindi"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi"), ("bn", "Bengali")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_bn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Question in Bengali"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_hi",
            field=models.TextField(
                blank=True, null=True, verbose_name="Question in Hindi"
            ),
        ),
    ]
